# Generated by Django 6.0.2 on 2026-05-25 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='profile_image',
            new_name='profile_image_url',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='featuredperson',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='inspirationvideo',
            old_name='thumbnail',
            new_name='thumbnail_url',
        ),
        migrations.RenameField(
            model_name='inspirationvideo',
            old_name='video',
            new_name='video_url',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='pagemedia',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='pagemedia',
            old_name='video',
            new_name='video_url',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='successstory',
            old_name='image',
            new_name='image_url',
        ),
    ]
