# Generated by Django 6.0.2 on 2026-05-10 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('id_pass_no', models.CharField(max_length=50, verbose_name='ID/Passport No')),
                ('starting_date', models.DateField()),
                ('residence', models.CharField(max_length=100)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='temp/')),
                ('profile_image_url', models.URLField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.CreateModel(
            name='partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('partners_description', models.TextField()),
                ('profile_logo', models.ImageField(blank=True, null=True, upload_to='temp/')),
                ('profile_logo_url', models.URLField(blank=True, max_length=250, null=True)),
                ('website_url', models.URLField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='core.employees')),
                ('program_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='core.program')),
            ],
        ),
        migrations.CreateModel(
            name='testimonials',
            fields=[
                ('testimonial_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('testimonial_message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='temp/')),
                ('image_url', models.URLField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='core.program')),
            ],
        ),
    ]
