# Generated by Django 6.0.2 on 2026-05-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employees_gallery_image_partners_testimonials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testimonials',
        ),
    ]
