# Generated by Django 6.0.2 on 2026-05-25 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blogpost_alter_donation_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
    ]
