# Generated by Django 6.0.2 on 2026-05-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_donation_event_payment_event_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_payment',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='volunteerpayment',
            name='paid',
        ),
        migrations.AddField(
            model_name='event_payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='calculated_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('payment_pending', 'Payment Pending'), ('paid', 'Paid'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('completed', 'Completed')], default='submitted', max_length=30),
        ),
        migrations.AddField(
            model_name='volunteerpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
