# Generated by Django 6.0.2 on 2026-05-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_event_payment_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('children', 'Children Program'), ('women', 'Women Empowerment')], max_length=20)),
                ('feature_type', models.CharField(choices=[('scholar', 'Scholar of the Week'), ('entrepreneur', 'Entrepreneur of the Month'), ('mentor', 'Mentor Spotlight')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('headline', models.CharField(max_length=150)),
                ('short_bio', models.TextField()),
                ('achievement', models.CharField(blank=True, max_length=255, null=True)),
                ('dream_or_goal', models.CharField(blank=True, max_length=255, null=True)),
                ('quote', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='temp/')),
                ('image_url', models.URLField(blank=True, max_length=250, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpactMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('children', 'Children Program'), ('women', 'Women Empowerment')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='InspirationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('children', 'Children Program'), ('women', 'Women Empowerment')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(help_text='YouTube, Vimeo, Cloudinary, or direct video URL', max_length=500)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='temp/')),
                ('thumbnail_url', models.URLField(blank=True, max_length=250, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('children', 'Children Program'), ('women', 'Women Empowerment')], max_length=20)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='temp/')),
                ('image_url', models.URLField(blank=True, max_length=250, null=True)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Page media',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('children', 'Children Program'), ('women', 'Women Empowerment')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('challenge', models.TextField()),
                ('intervention', models.TextField()),
                ('outcome', models.TextField()),
                ('quote', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='temp/')),
                ('image_url', models.URLField(blank=True, max_length=250, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Success stories',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='event_payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='calculated_fee',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='volunteerpayment',
            name='status',
        ),
        migrations.AddField(
            model_name='event_payment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerpayment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
