# Generated by Django 6.0.2 on 2026-05-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_event_payment_status_volunteer_calculated_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='response_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('addressed', 'Addressed'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate'), ('wontfix', "Won't Fix"), ('needsinfo', 'Needs Info'), ('accepted', 'Accepted'), ('reopened', 'Reopened')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
