# Generated by Codex on 2026-05-23

from django.db import migrations, models


def update_existing_currency(apps, schema_editor):
    Donation = apps.get_model('core', 'donation')
    Donation.objects.filter(currency='KES').update(currency='USD')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.RunPython(update_existing_currency, migrations.RunPython.noop),
    ]
