# Generated by Codex on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_set_donation_currency_usd'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('excerpt', models.TextField()),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='temp/')),
                ('image_url', models.URLField(blank=True, max_length=250, null=True)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
